# Generated by Django 4.2 on 2023-06-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Castle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Senq malt',
            field=models.IntegerField(default=0),
        ),
    ]
