# Generated by Django 4.2 on 2023-06-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_product_amount_in_store_castle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount_in_store',
            name='ST.George beer',
            field=models.IntegerField(default=0),
        ),
    ]
