# Generated by Django 4.2.2 on 2023-06-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_product_amount_in_store_castle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Castle',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Dopple',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='ST.George beer',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Senq malt',
        ),
    ]
