# Generated by Django 4.2.2 on 2023-06-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_remove_product_amount_in_store_castle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Castle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Dopple',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='ST.George beer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Senq malt',
            field=models.IntegerField(default=0),
        ),
    ]
