# Generated by Django 4.2.2 on 2023-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_product_amount_in_store_castle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount_in_store',
            name='walta',
            field=models.IntegerField(default=0),
        ),
    ]
