# Generated by Django 4.2.2 on 2023-06-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0009_product_amount_in_store_walta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Castle',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Dopple',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='ST.George beer',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Senq malt',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='walta',
        ),
    ]
