# Generated by Django 6.0.7 on 2026-07-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0012_remove_product_amount_in_store_castle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Dopple',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Senq malt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='walta',
            field=models.IntegerField(default=0),
        ),
    ]
