# Generated by Django 4.2 on 2023-06-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='Dopple',
        ),
    ]
