# Generated by Django 4.2.2 on 2023-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_customer_order_castle_customer_order_dopple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='walta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
