# Generated by Django 4.2.2 on 2023-06-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_customer_order_walta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='Castle',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='Dopple',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='ST.George beer',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='Senq malt',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='walta',
        ),
    ]
