# Generated by Django 4.2.2 on 2023-06-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_remove_customer_order_castle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='Castle',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='Dopple',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='ST.George beer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='Senq malt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
