# Generated by Django 6.0.7 on 2026-08-01 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_remove_customer_order_castle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelebirrTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(db_index=True, help_text='Unique transaction reference generated by our merchant system.', max_length=64, unique=True)),
                ('msf_order_id', models.CharField(blank=True, db_index=True, help_text='Transaction reference identifier generated by Telebirr platform.', max_length=128, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payment amount in Ethiopian Birr (ETB).', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('raw_response', models.JSONField(blank=True, help_text='Full JSON payload returned from Telebirr webhook callback.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Customer_order', models.ForeignKey(help_text='Associated Customer Order being paid for.', on_delete=django.db.models.deletion.CASCADE, related_name='telebirr_transactions', to='Customer.customer_order')),
            ],
            options={
                'verbose_name': 'Telebirr Transaction',
                'verbose_name_plural': 'Telebirr Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
