# Generated by Django 6.0.7 on 2026-08-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_remove_customer_order_castle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_transaction',
            name='currency',
            field=models.CharField(blank=True, default='ETB', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer_transaction',
            name='provider_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer_transaction',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer_transaction',
            name='MarchentId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_transaction',
            name='TransactionCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
