# Generated by Django 4.2 on 2023-06-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_order',
            name='Castle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent_order',
            name='Dopple',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent_order',
            name='Senq malt',
            field=models.IntegerField(default=0),
        ),
    ]
