# Generated by Django 4.2 on 2023-06-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_agent_order_castle_agent_order_dopple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_order',
            name='ST.George beer',
            field=models.IntegerField(default=0),
        ),
    ]
