# Generated by Django 4.2 on 2023-06-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0004_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Pofile/'),
        ),
    ]
