# Generated by Django 4.2.2 on 2023-06-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0006_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_order',
            name='Castle',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='Dopple',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='ST.George beer',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='Senq malt',
        ),
    ]
