# Generated by Django 4.2.2 on 2023-06-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0008_agent_order_castle_agent_order_dopple_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_order',
            name='Castle',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='Dopple',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='ST.George beer',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='Senq malt',
        ),
    ]
