# Generated by Django 4.2.2 on 2023-06-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0009_remove_agent_order_castle_remove_agent_order_dopple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_order',
            name='Castle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent_order',
            name='Dopple',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent_order',
            name='ST.George beer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent_order',
            name='Senq malt',
            field=models.IntegerField(default=0),
        ),
    ]
