# Generated by Django 4.2.2 on 2023-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0010_agent_order_castle_agent_order_dopple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_order',
            name='walta',
            field=models.IntegerField(default=0),
        ),
    ]
