# Generated by Django 6.0.7 on 2026-07-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0013_agent_order_castle_agent_order_dopple_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_order',
            name='Castle',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='Dopple',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='ST.George beer',
        ),
        migrations.RemoveField(
            model_name='agent_order',
            name='Senq malt',
        ),
    ]
